### ISSUE TITLE
Add accuracy and location provider to data

### ISSUE THREAD

**Issue by tacman** [survos/Traccar#1]
Add accuracy, local_time (and/or timezone), and location provider to the messages sent to the tracking server? 

Coordinate with @kcivey about the exact format, so that the tracking server that receives this data can be updated.

**Comment by anshul1235** [comment]
@kcivey can you provide me the format ! or we are changing it to json (which is more convenient)
please update me thanks

**Comment by kcivey** [comment]
OK, we should be handling the TRCCR2 socket messages on our end now.

**Comment by anshul1235** [comment]
resolved 
SHA 387c9a3333fbc6ee5cd921c768560c6fa8a53cba
