### ISSUE TITLE
If set, put content in status display

### ISSUE THREAD

**Issue by tacman** [survos/Traccar#10]
![image](https://cloud.githubusercontent.com/assets/619585/4813060/2e3a5312-5ec5-11e4-8411-f2ba72172dd2.png)

Just like email and server address show the email and server address, the other fields should only display the description if the value is empty.   Otherwise, it should display the value.

**Comment by anshul1235** [comment]
kindly check the changes.. it is resolved
- SHA : 51673c2dafe69872b4bed5b46a4fa9e3f5253c41
