### ISSUE TITLE
Restrict by time range

### ISSUE THREAD

**Issue by tacman** [survos/Traccar#5]
In order to save battery, we need to be able to restrict what times the app tracks.  There are several ways to do this, for now I'd like checkbox option on the settings page that is "Restrict by Time".  If that box is checked, then two other fields (disabled if not checked) are enabled that are start and stop times, either as two regular time fields, or if it's really easy, a range slider like:

![image](https://cloud.githubusercontent.com/assets/619585/4782413/0cf98edc-5cf1-11e4-8f1e-e747b2870556.png)

http://marcneuwirth.com/wp-content/uploads/2010/06/timeslider2.html

Someday we may wish to have multiple siders, e.g. for tracking someone to and from work, but not during their working hours (except maybe lunch).  Or to tracking differently during the weekends.  But for now a single time range is enough.

When Restrict by Time is enabled, the app should not check or send coordinates except during that time.   This should save battery.

**Comment by anshul1235** [comment]
Please check it , this is complete.. i am closing this issue now
- SHA : 95c4e089d444d56cdbefc207cbb9d769277dd6cd
