### ISSUE TITLE
SQLite table of points

### ISSUE THREAD

**Issue by tacman** [survos/Traccar#7]
Instead of pushing directly to the server, the app should store the data to a SQLite table, then an independent process should be pushing that data to the server when possible, notifiying the user if there's an issue (maybe by changing some status indicator from green to yellow or red).

The table should contain utc timestamp, localtime, local date, lat, long, and then a text blob (in JSON) of all the other data that we need but don't need to be searchable or sortable.  It should also contain something that indicates if (or when) the point was successfully uploaded to the server.

Finally, we should probably have some basic UI that lists the point count (by day?) and offers the option to clear the history.  

Eventually this SQLIte table will contain the data to be displayed on a map.

**Comment by anshul1235** [comment]
added local database wrappers and structures, 
- SHA 085852bb68760ccab22679dcc4f8ab2c4aee4a59

**Comment by anshul1235** [comment]
This issue has been resolved, Please test
- SHA 8fbc350127b90d886a0b620514485eda293ce2d4
