### ISSUE TITLE
Take screenshots, add to /graphics

### ISSUE THREAD

**Issue by tacman** [survos/Traccar#9]
We need graphic files suitable for uploading to Google Play.  We can use similar ones to Traccar for now:

https://play.google.com/store/apps/details?id=org.traccar.client

Please put the screenshots in the directory /graphics/screenhots and add them to the repo.

**Comment by anshul1235** [comment]
added
- SHA: 1b32b83fa12c01fbbd5400d56b91ac774de4b32e
